#website setting
title = "幻想サイクル"
baseURL = "http://blog.gensobunya.net/"
languageCode = "ja-jp"
canonifyURLs = false
#relativeURLs = true
theme = "mainroad"
googleAnalytics = "UA-72162915-1"
enableRobotsTXT = true

#system
contentDir = "content"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
hasCJKLanguage = true
defaultLayout = "post"
uglyurls = true


[Permalinks]
post = "/:year:month/:filename"

[taxonomies]
#category = "categories"
tag = "tags"

#START mainroad setting
[Params]
    subtitle = "シクロクロスとロードバイク、時々MTBと同人誌" # Subtitle of your site. Used in site header
    description = "シクロクロスとロードバイク、時々MTBと同人誌" # Description of your site. Used in meta description
    opengraph = true # Enable OpenGraph if true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false # Show authorbox at bottom of pages if true
    post_navigation = true # Show post navigation at bottom of pages if true
    postSections = ["post"] # the section pages to show on home page and the "Recent articles" widget
    #postSections = ["blog", "news"] # alternative that shows more than one section's pages
    dateformat = "2006-01-02" # change the format of dates

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent articles" widget
    recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
    categories = false # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

    # Enable "Social" widget, if any of "social_*" set a value
    #social_facebook = "username"
    social_twitter = "gen_sobunya"
    #social_linkedin = "username"
    #social_github = "username"
    #social_email = "example@example.com"

    adsense = true #Enable "Adsense" widget. (original function by Gen)
#END mainroad setting

